/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vNOBsuVjw",
    "aws_user_pools_web_client_id": "4dir9117usut4gehtk5a7aff0f",
    "oauth": {
        "domain": "halifaxfoodieusers.auth.us-east-1.amazoncognito.com"
    }
};


export default awsmobile;
